import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,lstat,realpath,rm,symlink,unlink} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {createHash,randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {install,update,rollback,uninstall,status,preview,recover} from '../installer/engine.mjs';
import {resolvePaths} from '../installer/paths.mjs';

const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const engineUrl=new URL('../installer/engine.mjs',import.meta.url).href;
const skill=version=>Buffer.from('---\nname: tansr\ndescription: synthetic installer discovery regression\n---\n'+version+'\n');
const entry=bytes=>({path:'SKILL.md',bytes:bytes.length,sha256:digest(bytes)});
const exists=p=>lstat(p).then(()=>true,error=>{if(error.code==='ENOENT')return false;throw error;});
async function json(file,value){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,JSON.stringify(value,null,2)+'\n');}
async function fixture(t){
  const parent=await realpath(tmpdir()),root=await mkdtemp(path.join(parent,'tansr-discovery-'));
  t.after(async()=>{const rel=path.relative(parent,root);assert.ok(rel.startsWith('tansr-discovery-')&&!rel.includes(path.sep));await rm(root,{recursive:true,force:true});});
  const skillsRoot=path.join(root,'project','.codebuddy','skills'),targetPath=path.join(skillsRoot,'tansr');
  return{root,skillsRoot,targetPath,legacyState:path.join(skillsRoot,'.tansr-installer-state')};
}
async function bundle(f,version){
  const payloadRoot=path.join(f.root,'payload-'+version),bytes=skill(version);
  await mkdir(payloadRoot);await writeFile(path.join(payloadRoot,'SKILL.md'),bytes);
  return{payloadRoot,manifest:{schemaVersion:1,name:'tansr',version,files:[entry(bytes)]}};
}
// This models the host's recursive SKILL.md discovery without excluding dot directories.
async function discover(root,relative=''){
  if(!await exists(root))return[];
  const found=[];
  for(const item of await readdir(root,{withFileTypes:true})){
    const name=relative?relative+'/'+item.name:item.name,file=path.join(root,item.name);
    assert.equal(item.isSymbolicLink(),false,'Discovery fixture must not follow links');
    if(item.isDirectory())found.push(...await discover(file,name));
    else if(item.isFile()&&item.name==='SKILL.md')found.push(name);
  }
  return found.sort();
}
async function snapshot(root,relative=''){
  if(!await exists(root))return[];
  const out=[];
  for(const item of await readdir(root,{withFileTypes:true})){
    const name=relative?relative+'/'+item.name:item.name,file=path.join(root,item.name),s=await lstat(file);
    assert.equal(s.isSymbolicLink(),false);
    out.push({path:name,kind:s.isDirectory()?'directory':'file',mtimeMs:s.mtimeMs,ino:s.ino,...(s.isFile()?{sha256:digest(await readFile(file))}:{})});
    if(s.isDirectory())out.push(...await snapshot(file,name));
  }
  return out.sort((a,b)=>a.path.localeCompare(b.path));
}
function record(version,bytes,txId){
  return{schemaVersion:1,name:'tansr',version,managedFiles:bytes?[entry(bytes)]:[],metadata:{host:'workbuddy',scope:'project',packageVersion:'0.1.1'},complete:true,installedAt:'2026-10-08T00:00:00.000Z',lastTransactionId:txId};
}
// Genuine 0.1.1 on-disk schema, not generated by the implementation under test.
async function legacy(f,{uninstalled=false,pending=false}={}){
  const a=skill('1.0.0'),b=skill('2.0.0'),c=skill('3.0.0'),first=randomUUID(),second=randomUUID();
  const before=record('1.0.0',a,null),installed=record('2.0.0',b,first);
  const completed={schemaVersion:1,txId:first,targetPath:f.targetPath,action:'update',phase:'committed',beforeRecord:before,afterRecord:installed,operations:[{path:'SKILL.md',before:entry(a),after:entry(b)}],createdDirectories:[]};
  await json(path.join(f.legacyState,'owner.json'),{schemaVersion:1,name:'tansr-installer',targetPath:f.targetPath,id:randomUUID()});
  await json(path.join(f.legacyState,'transactions',first,'transaction.json'),completed);
  await mkdir(path.join(f.legacyState,'transactions',first,'backup'));await mkdir(path.join(f.legacyState,'transactions',first,'stage'));
  await writeFile(path.join(f.legacyState,'transactions',first,'backup','SKILL.md'),a);
  let current=installed;
  if(uninstalled||pending){
    const next=record(pending?'3.0.0':null,pending?c:null,second);
    const journal={schemaVersion:1,txId:second,targetPath:f.targetPath,action:pending?'update':'uninstall',phase:pending?'applying':'committed',beforeRecord:installed,afterRecord:next,operations:[{path:'SKILL.md',before:entry(b),after:pending?entry(c):null}],createdDirectories:[]};
    await json(path.join(f.legacyState,'transactions',second,'transaction.json'),journal);
    await mkdir(path.join(f.legacyState,'transactions',second,'backup'));await mkdir(path.join(f.legacyState,'transactions',second,'stage'));
    await writeFile(path.join(f.legacyState,'transactions',second,'backup','SKILL.md'),b);
    if(pending){await mkdir(f.targetPath,{recursive:true});await writeFile(path.join(f.legacyState,'transactions',second,'stage','SKILL.md'),c);await json(path.join(f.legacyState,'journal.json'),journal);}
    else current=next;
  }else{
    await mkdir(f.targetPath,{recursive:true});await writeFile(path.join(f.targetPath,'SKILL.md'),b);
  }
  await json(path.join(f.legacyState,'record.json'),current);
  return{before,installed,current,first,second};
}
async function assertMigrated(f){
  const paths=await resolvePaths(f.targetPath);
  assert.equal(path.dirname(paths.state),path.dirname(f.skillsRoot));
  assert.match(path.basename(paths.state),/^\.tansr-installer-state-[0-9a-f]{16}$/);
  assert.equal(await exists(paths.state),true);
  assert.equal(await exists(path.join(f.legacyState,'transactions')),false);
  const marker=JSON.parse(await readFile(path.join(f.legacyState,'owner.json'),'utf8'));
  assert.equal(marker.name,'tansr-installer-migrated');
  assert.equal((await status(f)).migrationRequired,false);
  return paths.state;
}

test('recursive discovery sees only the active entry throughout install, update, rollback and uninstall',async t=>{
  const f=await fixture(t),a=await bundle(f,'1.0.0'),b=await bundle(f,'2.0.0');
  await mkdir(path.join(f.skillsRoot,'unrelated'),{recursive:true});await writeFile(path.join(f.skillsRoot,'unrelated','SKILL.md'),'other user skill');
  const seen=[];
  const _onStep=async name=>{const found=await discover(f.skillsRoot);seen.push(name);assert.ok(found.every(p=>['tansr/SKILL.md','unrelated/SKILL.md'].includes(p)),JSON.stringify({name,found}));};
  for(const operation of [()=>install({...f,...a,_onStep}),()=>update({...f,...b,_onStep}),()=>rollback({...f,_onStep})]){
    const result=await operation();assert.equal(result.ok,true);assert.deepEqual(await discover(f.skillsRoot),['tansr/SKILL.md','unrelated/SKILL.md']);
  }
  assert.equal((await uninstall({...f,_onStep})).ok,true);
  assert.deepEqual(await discover(f.skillsRoot),['unrelated/SKILL.md']);
  assert.ok(seen.includes('prepared')&&seen.includes('backed-up')&&seen.includes('committed'));
  assert.equal(await readFile(path.join(f.skillsRoot,'unrelated','SKILL.md'),'utf8'),'other user skill');
});

test('status and preview report a legacy installed state without moving files or changing timestamps',async t=>{
  const f=await fixture(t);await legacy(f);const next=await bundle(f,'3.0.0'),before=await snapshot(f.skillsRoot);
  const s=await status(f);assert.equal(s.status,'installed');assert.equal(s.migrationRequired,true);
  const p=await preview({...f,...next});assert.equal(p.status,'ready');assert.equal(p.migrationRequired,true);
  assert.deepEqual(await snapshot(f.skillsRoot),before);
  assert.equal(await exists((await resolvePaths(f.targetPath)).state),false);
});

test('legacy installed migration preserves historical rollback bytes and removes all backup skills from discovery',async t=>{
  const f=await fixture(t);await legacy(f);
  const result=await rollback(f);assert.equal(result.status,'rolled-back');
  const state=await assertMigrated(f);
  assert.deepEqual(await discover(f.skillsRoot),['tansr/SKILL.md']);
  assert.deepEqual(await readFile(path.join(f.targetPath,'SKILL.md')),skill('1.0.0'));
  assert.ok((await discover(state)).length>=1,'History remains recoverable outside discovery root');
  await uninstall(f);assert.deepEqual(await discover(f.skillsRoot),[]);
});

test('legacy installed update migrates while preserving edited and unknown target files',async t=>{
  const f=await fixture(t);await legacy(f);const next=await bundle(f,'3.0.0');
  await writeFile(path.join(f.targetPath,'SKILL.md'),'user-modified');
  await writeFile(path.join(f.targetPath,'notes.txt'),'USER NOTES');
  const result=await update({...f,...next});assert.equal(result.status,'partial');assert.equal(result.exitCode,2);
  await assertMigrated(f);
  assert.equal(await readFile(path.join(f.targetPath,'SKILL.md'),'utf8'),'user-modified');
  assert.equal(await readFile(path.join(f.targetPath,'notes.txt'),'utf8'),'USER NOTES');
  assert.deepEqual(await discover(f.skillsRoot),['tansr/SKILL.md']);
});

test('legacy uninstalled state is read-only on status and can migrate through managed uninstall',async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});const before=await snapshot(f.skillsRoot);
  const s=await status(f);assert.equal(s.status,'uninstalled');assert.equal(s.migrationRequired,true);
  assert.deepEqual(await snapshot(f.skillsRoot),before);
  assert.equal((await uninstall(f)).status,'uninstalled');await assertMigrated(f);
  assert.deepEqual(await discover(f.skillsRoot),[]);
});

test('reinstall over legacy uninstalled state migrates before staging the new active entry',async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});const next=await bundle(f,'3.0.0');
  const result=await install({...f,...next,_onStep:async name=>{if(name.startsWith('migration-'))return;const found=await discover(f.skillsRoot);assert.ok(found.every(p=>p==='tansr/SKILL.md'),JSON.stringify(found));}});
  assert.equal(result.status,'installed');await assertMigrated(f);
  assert.deepEqual(await discover(f.skillsRoot),['tansr/SKILL.md']);
  assert.deepEqual(await readFile(path.join(f.targetPath,'SKILL.md')),skill('3.0.0'));
});

test('explicit recovery migrates an interrupted legacy transaction and restores its registered bytes',async t=>{
  const f=await fixture(t);await legacy(f,{pending:true});
  assert.equal((await status(f)).recoveryRequired,true);
  const recovered=await recover(f);assert.equal(recovered.status,'recovered');await assertMigrated(f);
  assert.deepEqual(await readFile(path.join(f.targetPath,'SKILL.md')),skill('2.0.0'));
  assert.deepEqual(await discover(f.skillsRoot),['tansr/SKILL.md']);
  assert.equal((await recover(f)).status,'nothing-to-recover');
});

test('unknown legacy state files prevent migration and remain byte-for-byte in their original location',async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});await writeFile(path.join(f.legacyState,'.env'),'SYNTHETIC_DO_NOT_MIGRATE=keep');
  const before=await snapshot(f.skillsRoot);
  await assert.rejects(uninstall(f),error=>{assert.equal(error.code,'STATE_CONFLICT');return true;});
  assert.deepEqual(await snapshot(f.skillsRoot),before);
  assert.equal(await exists((await resolvePaths(f.targetPath)).state),false);
});

test('null legacy ownership is rejected without mutation or an unclassified exception',async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});
  await writeFile(path.join(f.legacyState,'owner.json'),'null\n');
  const before=await snapshot(f.root);
  for(const operation of [status,recover,uninstall]){
    await assert.rejects(operation(f),error=>{assert.equal(error.code,'STATE_CONFLICT');return true;});
    assert.deepEqual(await snapshot(f.root),before);
  }
});

test('a file added after migration preparation is not moved or adopted by recovery',async t=>{
  const f=await fixture(t),old=await legacy(f,{uninstalled:true});
  const relative=path.join('transactions',old.first,'backup','unknown.txt');
  const unknown=path.join(f.legacyState,relative);
  await assert.rejects(uninstall({...f,_onStep:async name=>{
    if(name==='migration-prepared')await writeFile(unknown,'USER FILE AFTER PREPARATION');
  }}),error=>{assert.equal(error.code,'MIGRATION_CONFLICT');return true;});
  assert.equal(await readFile(unknown,'utf8'),'USER FILE AFTER PREPARATION');
  assert.equal(await exists(path.join((await resolvePaths(f.targetPath)).state,relative)),false);
  await assert.rejects(recover(f),error=>{assert.equal(error.code,'MIGRATION_CONFLICT');return true;});
  assert.equal(await readFile(unknown,'utf8'),'USER FILE AFTER PREPARATION');
  assert.deepEqual(await readFile(path.join(path.dirname(unknown),'SKILL.md')),skill('1.0.0'));
});

test('legacy linked files are rejected without following or relocating them',async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});
  const outside=path.join(f.root,'outside');await mkdir(outside);await writeFile(path.join(outside,'SKILL.md'),'OUTSIDE');
  const link=path.join(f.legacyState,'unexpected-link');await symlink(outside,link,process.platform==='win32'?'junction':'dir');
  try{
    await assert.rejects(uninstall(f),error=>{assert.equal(error.code,'UNSAFE_LINK');return true;});
    assert.equal((await lstat(link)).isSymbolicLink(),true);
    assert.equal(await readFile(path.join(outside,'SKILL.md'),'utf8'),'OUTSIDE');
  }finally{await unlink(link);}
});

for(const point of ['migration-prepared','migration-moved','migration-committed'])test(`interrupted legacy migration at ${point} is explicit and recoverable without resurrecting a Skill`,async t=>{
  const f=await fixture(t);await legacy(f,{uninstalled:true});
  const child=spawnSync(process.execPath,['--input-type=module','-e',`import {uninstall} from ${JSON.stringify(engineUrl)};await uninstall({...${JSON.stringify(f)},_onStep(name){if(name===${JSON.stringify(point)})process.exit(77);}});`],{encoding:'utf8',timeout:30000});
  assert.equal(child.error,undefined);assert.equal(child.status,77,child.stderr);
  const before=await snapshot(f.root);
  await status(f);
  assert.deepEqual(await snapshot(f.root),before,'Status must not finish or roll back migration');
  await recover(f);await assertMigrated(f);
  assert.deepEqual(await discover(f.skillsRoot),[]);
  assert.equal((await status(f)).status,'uninstalled');
  assert.equal((await recover(f)).status,'nothing-to-recover');
});

