import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,lstat,link,symlink,readdir,realpath} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {once} from 'node:events';
import {install,preview,status,update,rollback,uninstall,recover} from '../installer/engine.mjs';
import {validateManifest} from '../installer/manifest.mjs';

const engineUrl=new URL('../installer/engine.mjs',import.meta.url).href;
const digest=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t){const root=await mkdtemp(path.join(await realpath(tmpdir()),'tansr-engine-'));t.after(()=>rm(root,{recursive:true,force:true}));return{root,targetPath:path.join(root,'项目 空格','tansr')};}
async function bundle(root,version,values){const payloadRoot=path.join(root,`payload-${version}`);await mkdir(payloadRoot);const files=[];for(const [p,text]of Object.entries(values)){const b=Buffer.from(text);await mkdir(path.dirname(path.join(payloadRoot,p)),{recursive:true});await writeFile(path.join(payloadRoot,p),b);files.push({path:p,bytes:b.length,sha256:digest(b)});}return{payloadRoot,manifest:{schemaVersion:1,name:'tansr',version,files}};}
const rejection=code=>error=>{assert.equal(error.code,code);return true;};
async function content(target,p='SKILL.md'){return readFile(path.join(target,p),'utf8');}
async function exists(p){return lstat(p).then(()=>true,e=>{if(e.code==='ENOENT')return false;throw e;});}

test('preview is read-only; install verifies bytes, is idempotent and uninstall is bounded',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'first','references/a.md':'A','.env.example':'PUBLIC=example'}),o={...f,...b,metadata:{host:'codex',scope:'project'}};const p=await preview(o);assert.equal(p.status,'ready');assert.equal(await exists(path.dirname(f.targetPath)),false);const i=await install(o);assert.equal(i.filesInstalled,true);assert.equal(i.staticStructureValid,true);assert.equal(await content(f.targetPath),'first');assert.equal((await install(o)).status,'up-to-date');assert.equal((await status(f)).status,'installed');assert.equal((await uninstall(f)).status,'uninstalled');assert.equal(await exists(f.targetPath),false);assert.equal((await status(f)).status,'uninstalled');});

test('update and rollback use only registered bytes; payload code is never executed',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old','obsolete.txt':'remove','run.mjs':'throw new Error("DO NOT EXECUTE")'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new','added.txt':'add'});await install({...f,...a});await update({...f,...b});assert.equal(await content(f.targetPath),'new');assert.equal(await exists(path.join(f.targetPath,'obsolete.txt')),false);await rollback(f);assert.equal(await content(f.targetPath),'old');assert.equal(await content(f.targetPath,'obsolete.txt'),'remove');assert.equal(await exists(path.join(f.targetPath,'added.txt')),false);assert.equal((await status(f)).version,'1.0.0');});

test('update/uninstall retain changed, deleted, unknown files and unknown empty directories',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old','keep.txt':'keep','deleted.txt':'gone'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new','keep.txt':'new keep','deleted.txt':'replace','new.txt':'new'});await install({...f,...a});await writeFile(path.join(f.targetPath,'SKILL.md'),'user edit');await rm(path.join(f.targetPath,'deleted.txt'));await writeFile(path.join(f.targetPath,'.env'),'USER_SECRET=must-not-be-read-or-copied');await mkdir(path.join(f.targetPath,'unknown-empty'));const u=await update({...f,...b});assert.equal(u.exitCode,2);assert.equal(u.status,'partial');assert.equal(u.filesInstalled,false);assert.equal(await content(f.targetPath),'user edit');assert.equal(await content(f.targetPath,'keep.txt'),'new keep');assert.equal(await exists(path.join(f.targetPath,'deleted.txt')),false);assert(u.preserved.some(x=>x.reason==='user-deleted'));const remove=await uninstall(f);assert.equal(remove.exitCode,2);assert.equal(await content(f.targetPath),'user edit');assert.equal(await exists(path.join(f.targetPath,'unknown-empty')),true);assert.equal(await content(f.targetPath,'.env'),'USER_SECRET=must-not-be-read-or-copied');assert.equal(await exists(path.join(f.targetPath,'keep.txt')),false);const all=await readdir(path.join(path.dirname(f.targetPath),'.tansr-installer-state','transactions'),{recursive:true});assert.equal(all.some(p=>p.endsWith('.env')),false);});

test('unregistered same-name target is never adopted, including empty directory',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'payload'});await mkdir(f.targetPath,{recursive:true});await assert.rejects(install({...f,...b}),rejection('TARGET_CONFLICT'));assert.equal(await exists(path.join(path.dirname(f.targetPath),'.tansr-installer-state')),false);});

test('bad payload is rejected before any target/state creation',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'original'});await writeFile(path.join(b.payloadRoot,'SKILL.md'),'tampered');await assert.rejects(install({...f,...b}),rejection('PAYLOAD_INTEGRITY'));assert.equal(await exists(path.dirname(f.targetPath)),false);});

test('manifest rejects traversal, Windows names, source aliases and directory case collisions',()=>{const entry=p=>({path:p,bytes:0,sha256:digest('')});for(const p of ['../escape','/absolute','C:/escape','a\\b','x:stream','CON.txt','x.','trailing ','a/../b','.env','.env.local'])assert.throws(()=>validateManifest({schemaVersion:1,name:'tansr',version:'1.0.0',files:[entry(p)]}));for(const names of [['A','a'],['a','a/b'],['Dir/a','dir/b']])assert.throws(()=>validateManifest({schemaVersion:1,name:'tansr',version:'1.0.0',files:names.map(entry)}));assert.throws(()=>validateManifest({schemaVersion:1,name:'tansr',version:'1.0.0',files:[{...entry('a'),source:'../bad'}]}));assert.throws(()=>validateManifest({schemaVersion:1,name:'tansr',version:'1.0.0',files:[{...entry('a'),source:'same'},{...entry('b'),source:'same'}]}));});

test('pack-safe source alias installs original logical .gitignore bytes',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'assets/demo/tansr.gitignore':'node_modules/\n.env\n'});b.manifest.files[0].source=b.manifest.files[0].path;b.manifest.files[0].path='assets/demo/.gitignore';await install({...f,...b});assert.equal(await content(f.targetPath,'assets/demo/.gitignore'),'node_modules/\n.env\n');assert.equal(await exists(path.join(f.targetPath,'assets/demo/tansr.gitignore')),false);});

test('payload hardlink, target hardlink, and ancestor junction are rejected',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'safe'}),outside=path.join(f.root,'outside.txt');await writeFile(outside,'safe');await rm(path.join(b.payloadRoot,'SKILL.md'));await link(outside,path.join(b.payloadRoot,'SKILL.md'));await assert.rejects(install({...f,...b}),rejection('UNSAFE_LINK'));await rm(path.join(b.payloadRoot,'SKILL.md'));await writeFile(path.join(b.payloadRoot,'SKILL.md'),'safe');await install({...f,...b});await rm(path.join(f.targetPath,'SKILL.md'));await link(outside,path.join(f.targetPath,'SKILL.md'));await assert.rejects(uninstall(f),rejection('UNSAFE_LINK'));assert.equal(await readFile(outside,'utf8'),'safe');const actual=path.join(f.root,'actual');await mkdir(actual);const alias=path.join(f.root,'alias');await symlink(actual,alias,process.platform==='win32'?'junction':'dir');await assert.rejects(install({...b,targetPath:path.join(alias,'tansr')}),rejection('UNSAFE_LINK'));});

test('caught disk/publish failure rolls back under held lock',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old','other':'old other'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new','other':'new other'});await install({...f,...a});await assert.rejects(update({...f,...b,_onStep(name){if(name==='backed-up')throw new Error('injected ENOSPC');}}),rejection('IO_ERROR'));assert.equal(await content(f.targetPath),'old');assert.equal(await content(f.targetPath,'other'),'old other');assert.equal((await status(f)).version,'1.0.0');assert.equal((await recover(f)).status,'nothing-to-recover');});

for(const point of ['prepared','backed-up','published-file','before-commit','committed'])test(`real process interruption at ${point} requires explicit bounded recovery`,async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old','other':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new','other':'new'});await install({...f,...a});const code=`import {update} from ${JSON.stringify(engineUrl)}; await update({...${JSON.stringify({...f,...b})},_onStep(name){if(name===${JSON.stringify(point)})process.exit(77);}});`;const child=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8'});assert.equal(child.status,77,child.stderr);assert.equal((await status(f)).recoveryRequired,true);await assert.rejects(update({...f,...b}),rejection('RECOVERY_REQUIRED'));const restored=await recover(f);assert.equal(restored.status,point==='committed'?'commit-recovered':'recovered');assert.equal(await content(f.targetPath),point==='committed'?'new':'old');assert.equal(await content(f.targetPath,'other'),point==='committed'?'new':'old');assert.equal((await recover(f)).status,'nothing-to-recover');});

test('independent live process lock cannot be stolen by install or recover',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'one'});const code=`import {install} from ${JSON.stringify(engineUrl)};await install({...${JSON.stringify({...f,...b})},async _onStep(name){if(name==='prepared'){process.send('locked');await new Promise(r=>process.once('message',r));}}});`;const child=spawn(process.execPath,['--input-type=module','-e',code],{stdio:['ignore','pipe','pipe','ipc']});t.after(()=>{if(child.exitCode===null)child.kill();});await once(child,'message');await assert.rejects(install({...f,...b}),rejection('LOCKED'));await assert.rejects(recover(f),rejection('LOCKED'));const done=once(child,'exit');child.send('continue');assert.equal((await done)[0],0);assert.equal((await status(f)).filesInstalled,true);});

test('rollback refuses user edits after update and preserves both versions',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});await update({...f,...b});await writeFile(path.join(f.targetPath,'SKILL.md'),'user after update');await assert.rejects(rollback(f),rejection('USER_CHANGED'));assert.equal(await content(f.targetPath),'user after update');});

test('tampered journal cannot remove an unrelated unknown directory',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});const child=spawnSync(process.execPath,['--input-type=module','-e',`import{update}from ${JSON.stringify(engineUrl)};await update({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='prepared')process.exit(77)}})`]);assert.equal(child.status,77);await mkdir(path.join(f.targetPath,'unknown-empty'));const p=path.join(path.dirname(f.targetPath),'.tansr-installer-state','journal.json'),j=JSON.parse(await readFile(p,'utf8'));j.createdDirectories.push('unknown-empty');await writeFile(p,JSON.stringify(j));await assert.rejects(recover(f),rejection('STATE_CORRUPT'));assert.equal(await exists(path.join(f.targetPath,'unknown-empty')),true);assert.equal(await content(f.targetPath),'old');});

test('user change at publication boundary is preserved with recovery journal',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});await assert.rejects(update({...f,...b,async _onStep(n){if(n==='before-commit')await writeFile(path.join(f.targetPath,'SKILL.md'),'concurrent edit');}}),rejection('RECOVERY_REQUIRED'));assert.equal(await content(f.targetPath),'concurrent edit');assert.equal((await status(f)).recoveryRequired,true);await assert.rejects(recover(f),rejection('RECOVERY_CONFLICT'));});

test('partial version with no remaining managed files never becomes complete status',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});await rm(path.join(f.targetPath,'SKILL.md'));assert.equal((await update({...f,...b})).exitCode,2);const s=await status(f);assert.equal(s.ok,false);assert.equal(s.exitCode,2);assert.equal(s.filesInstalled,false);assert.equal(s.status,'modified');});

test('update refuses case-equivalent existing directory aliases',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'dir/old':'old'}),b=await bundle(f.root,'2.0.0',{'dir/old':'old','Dir/new':'new'});await install({...f,...a});await assert.rejects(update({...f,...b}),rejection('CASE_COLLISION'));assert.equal(await content(f.targetPath,'dir/old'),'old');assert.equal(await exists(path.join(f.targetPath,'Dir/new')),false);});

test('source traversal, source hardlinks, target and state junctions are refused',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'safe':'text'});b.manifest.files[0].source='../outside';await assert.rejects(install({...f,...b}),rejection('UNSAFE_PATH'));b.manifest.files[0].source='safe';const real=path.join(f.root,'actual');await mkdir(real);await mkdir(path.dirname(f.targetPath),{recursive:true});await symlink(real,path.join(path.dirname(f.targetPath),'.tansr-installer-state'),process.platform==='win32'?'junction':'dir');await assert.rejects(install({...f,...b}),rejection('UNSAFE_LINK'));assert.deepEqual(await readdir(real),[]);});

test('two recover processes cannot unlink the new owner after claiming one dead nonce',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});const dead=spawnSync(process.execPath,['--input-type=module','-e',`import{update}from ${JSON.stringify(engineUrl)};await update({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='backed-up')process.exit(77)}})`]);assert.equal(dead.status,77);const code=`import{recover}from ${JSON.stringify(engineUrl)};await recover({...${JSON.stringify(f)},async _onStep(n){if(n==='recovery-claimed'){process.send('claimed');await new Promise(r=>process.once('message',r));}}});`;const first=spawn(process.execPath,['--input-type=module','-e',code],{stdio:['ignore','pipe','pipe','ipc']});t.after(()=>{if(first.exitCode===null)first.kill();});await once(first,'message');await assert.rejects(recover(f),rejection('LOCKED'));const done=once(first,'exit');first.send('continue');assert.equal((await done)[0],0);assert.equal(await content(f.targetPath),'old');assert.equal((await status(f)).filesInstalled,true);});

test('uninstall interruption restores original bytes and never touches unknown siblings',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old','reference/a':'A'});await install({...f,...a});await writeFile(path.join(f.targetPath,'user.txt'),'USER');const c=spawnSync(process.execPath,['--input-type=module','-e',`import{uninstall}from ${JSON.stringify(engineUrl)};await uninstall({...${JSON.stringify(f)},_onStep(n){if(n==='backed-up')process.exit(77)}})`]);assert.equal(c.status,77);await recover(f);assert.equal(await content(f.targetPath),'old');assert.equal(await content(f.targetPath,'user.txt'),'USER');});

test('first install interruption recovers without adopting an unknown directory',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'nested/SKILL.md':'first'});const c=spawnSync(process.execPath,['--input-type=module','-e',`import{install}from ${JSON.stringify(engineUrl)};await install({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='published-file')process.exit(77)}})`]);assert.equal(c.status,77);await assert.rejects(uninstall(f),rejection('RECOVERY_REQUIRED'));await recover(f);assert.equal(await exists(f.targetPath),false);assert.equal((await install({...f,...b})).filesInstalled,true);});

test('committed recovery rejects forged record claims absent from transaction operations',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'first'});const c=spawnSync(process.execPath,['--input-type=module','-e',`import{install}from ${JSON.stringify(engineUrl)};await install({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='committed')process.exit(77)}})`]);assert.equal(c.status,77);const file=path.join(path.dirname(f.targetPath),'.tansr-installer-state','journal.json'),j=JSON.parse(await readFile(file,'utf8'));j.afterRecord.managedFiles.push({path:'not-real',bytes:0,sha256:digest('')});await writeFile(file,JSON.stringify(j));await assert.rejects(recover(f),rejection('STATE_CORRUPT'));assert.equal(await content(f.targetPath),'first');});

test('rollback rejects a partial update that would re-register a user-deleted file',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'a':'a1','b':'b1'}),b=await bundle(f.root,'2.0.0',{'a':'a2','b':'b2'});await install({...f,...a});await rm(path.join(f.targetPath,'a'));await update({...f,...b});await assert.rejects(rollback(f),rejection('ROLLBACK_CONFLICT'));assert.equal(await exists(path.join(f.targetPath,'a')),false);assert.equal(await content(f.targetPath,'b'),'b2');assert.equal((await status(f)).filesInstalled,false);});

test('historical committed journal cannot overwrite current ownership record',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'a':'a1'}),b=await bundle(f.root,'2.0.0',{'a':'a2'}),c=await bundle(f.root,'3.0.0',{'a':'a2','c':'c3'});await install({...f,...a});await update({...f,...b});const state=path.join(path.dirname(f.targetPath),'.tansr-installer-state'),oldRecord=JSON.parse(await readFile(path.join(state,'record.json'),'utf8')),oldJournal=await readFile(path.join(state,'transactions',oldRecord.lastTransactionId,'transaction.json'));await update({...f,...c});const current=await readFile(path.join(state,'record.json'));await writeFile(path.join(state,'journal.json'),oldJournal);await assert.rejects(recover(f),rejection('STATE_CORRUPT'));assert.deepEqual(await readFile(path.join(state,'record.json')),current);assert.equal(await content(f.targetPath,'c'),'c3');});

test('unchanged managed files are rechecked before reporting a complete commit',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'a':'a1','b':'b1'}),b=await bundle(f.root,'2.0.0',{'a':'a1','b':'b2'});await install({...f,...a});await assert.rejects(update({...f,...b,async _onStep(n){if(n==='before-commit')await writeFile(path.join(f.targetPath,'a'),'user');}}),rejection('USER_CHANGED'));assert.equal(await content(f.targetPath,'a'),'user');assert.equal(await content(f.targetPath,'b'),'b1');assert.equal((await status(f)).filesInstalled,false);});

test('recovery preserves a directory replaced after an interrupted install',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'nested/SKILL.md':'first'});const c=spawnSync(process.execPath,['--input-type=module','-e',`import{install}from ${JSON.stringify(engineUrl)};await install({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='published-file')process.exit(77)}})`]);assert.equal(c.status,77);const dir=path.join(f.targetPath,'nested');const prior=await readFile(path.join(dir,'SKILL.md'));await rm(dir,{recursive:true});await mkdir(dir);await writeFile(path.join(dir,'SKILL.md'),prior);await assert.rejects(recover(f),rejection('RECOVERY_CONFLICT'));assert.equal(await exists(dir),true);});

test('public release baseline arrays persist; arbitrary metadata fields are rejected',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'first'}),metadata={packageName:'@tansr/skill',packageVersion:'0.1.0',skillVersion:'0.1.0',host:'codex',scope:'project',templateBaselines:[{id:'web',version:'0.1.0'}],runtimeBaselines:[{id:'sdk',name:'@tansr/sdk',version:'0.18.1'}]};await install({...f,...b,metadata});const r=JSON.parse(await readFile(path.join(path.dirname(f.targetPath),'.tansr-installer-state','record.json'),'utf8'));assert.deepEqual(r.metadata,metadata);await assert.rejects(install({...f,...b,metadata:{...metadata,apiKey:'not-allowed'}}),rejection('INVALID_METADATA'));await assert.rejects(install({...f,...b,metadata:{runtimeBaselines:[{id:'sdk',version:'0.18.1',token:'not-allowed'}]}}),rejection('INVALID_METADATA'));});

test('unknown empty state directory and truncated ownership are never adopted',async t=>{const f=await fixture(t),b=await bundle(f.root,'1.0.0',{'SKILL.md':'first'}),state=path.join(path.dirname(f.targetPath),'.tansr-installer-state');await mkdir(state,{recursive:true});await assert.rejects(install({...f,...b}),rejection('STATE_CONFLICT'));assert.deepEqual(await readdir(state),[]);await writeFile(path.join(state,'owner.json'),'{');await assert.rejects(install({...f,...b}),rejection('STATE_CORRUPT'));assert.equal(await readFile(path.join(state,'owner.json'),'utf8'),'{');});

test('a process crash during recovery claim can advance to a new exclusive claim',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'old'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'new'});await install({...f,...a});const dead=spawnSync(process.execPath,['--input-type=module','-e',`import{update}from ${JSON.stringify(engineUrl)};await update({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='backed-up')process.exit(77)}})`]);assert.equal(dead.status,77);const claim=spawnSync(process.execPath,['--input-type=module','-e',`import{recover}from ${JSON.stringify(engineUrl)};await recover({...${JSON.stringify(f)},_onStep(n){if(n==='recovery-claimed')process.exit(78)}})`]);assert.equal(claim.status,78);await recover(f);assert.equal(await content(f.targetPath),'old');const claims=await readdir(path.join(path.dirname(f.targetPath),'.tansr-installer-state','recovery-claims'));assert.equal(claims.length,2);});

test('committed recovery checks unchanged managed files before readiness=true',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'a':'a1','b':'b1'}),b=await bundle(f.root,'2.0.0',{'a':'a1','b':'b2'});await install({...f,...a});const c=spawnSync(process.execPath,['--input-type=module','-e',`import{update}from ${JSON.stringify(engineUrl)};await update({...${JSON.stringify({...f,...b})},_onStep(n){if(n==='committed')process.exit(77)}})`]);assert.equal(c.status,77);await writeFile(path.join(f.targetPath,'a'),'user');await assert.rejects(recover(f),rejection('RECOVERY_CONFLICT'));assert.equal(await content(f.targetPath,'a'),'user');});

test('unknown directory cannot be adopted by adding a child then removed on uninstall',async t=>{const f=await fixture(t),a=await bundle(f.root,'1.0.0',{'SKILL.md':'v1'}),b=await bundle(f.root,'2.0.0',{'SKILL.md':'v2','custom/new.txt':'new'});await install({...f,...a});await mkdir(path.join(f.targetPath,'custom'));const u=await update({...f,...b});assert.equal(u.status,'partial');assert.equal(await exists(path.join(f.targetPath,'custom/new.txt')),false);await uninstall(f);assert.equal(await exists(path.join(f.targetPath,'custom')),true);});
